name: Maven Migration Test

on:
  workflow_dispatch:

jobs:
  migration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Set execution permissions
        run: |
          chmod +x migrate-to-maven.sh
          chmod +x migrate-source.sh
          chmod +x migrate-resources.sh
          chmod +x update-packages.sh
          chmod +x update-imports.sh

      - name: Run migration script
        run: ./migrate-to-maven.sh

      - name: Verify Maven build
        run: mvn clean compile
